[colors.primary]
background = '#262427'
foreground = '#fcfcfa'

[colors.cursor]
text = '#000000'
cursor = '#fcfcfa'

[colors.normal]
black   = '#262427'
red     = '#ff7272'
green   = '#bcdf59'
yellow  = '#ffca58'
blue    = '#49cae4'
magenta = '#a093e2'
cyan    = '#aee8f4'
white   = '#fcfcfa'

[colors.bright]
black   = '#545452'
red     = '#ff8787'
green   = '#c6e472'
yellow  = '#ffd271'
blue    = '#64d2e8'
magenta = '#aea3e6'
cyan    = '#baebf6'
white   = '#fcfcfa'
